## **5. Pandas 데이터 조작 실습**

### **패키지 임포트 및 DataFrame 객체 생성**
가장 먼저 데이터 조작에 유용한 파이썬 라이브러리인 Pandas 패키지를 `pd`라는 이름으로 임포트합니다. 
이후 `.csv` 파일을 인덱싱된 2차원 배열 구조인 `DataFrame` 객체로 불러옵니다.

In [1]:
import pandas as pd
import numpy as np

# 데이터 로드 (csv 파일 읽기)
df = pd.read_csv('./data/AirQualityUCI_refined.csv')

# 데이터의 첫 5행을 확인하여 올바르게 로드되었는지 확인
df.head()

,Datetime,CO(GT),PT08.S1(CO),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),RH,AH,C6H6(GT)
0,2004-03-10 18:00:00,2.6,1360.0,1046.0,166.0,1056.0,113.0,1692.0,1268.0,48.9,0.7578,11.9
1,2004-03-10 19:00:00,2.0,1292.0,955.0,103.0,1174.0,92.0,1559.0,972.0,47.7,0.7255,9.4
2,2004-03-10 20:00:00,2.2,1402.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,54.0,0.7502,9.0
3,2004-03-10 21:00:00,2.2,1376.0,948.0,172.0,1092.0,122.0,1584.0,1203.0,60.0,0.7867,9.2
4,2004-03-10 22:00:00,1.6,1272.0,836.0,131.0,1205.0,116.0,1490.0,1110.0,59.6,0.7888,6.5

### **Pandas 객체의 주요 속성 확인 (Main Attributes)**
Pandas 객체가 기본적으로 제공하는 주요 속성을 확인합니다.
* `.index`: 행의 인덱스 값을 반환합니다.
* `.columns`: DataFrame의 열 레이블(Column 명)을 반환합니다.
* `.values`: 데이터의 값들을 NumPy 2차원 배열(ndarray) 형태로 반환합니다.

In [ ]:
# 행 인덱스 반환
df.index

In [ ]:
# 열 레이블 반환
df.columns

In [ ]:
# 값들을 NumPy 배열로 반환 (너무 길어지므로 첫 2행만 출력)
df.values

### **Series 객체 조작 (Dictionary Style)**
DataFrame은 인덱스를 공유하는 1차원 배열인 `Series` 객체들의 집합과 같습니다. 
파이썬의 Dictionary 구조와 유사하게 열 이름(Key)을 통해 특정 Series를 선택하거나, 새로운 데이터를 추가(Reassignment)할 수 있습니다.

In [3]:
# 'CO(GT)' 열을 하나의 Series 객체로 선택
co_series = df['CO(GT)']
print(type(co_series))
print("CO(GT) Series 첫 3개 값:\n", co_series.head(3))

# Dictionary 스타일의 새로운 데이터 열 추가
# 기존 CO(GT) 값에 2를 곱한 새로운 열 생성
df['CO_Double'] = df['CO(GT)'] * 2

print("\n새로운 열 추가 확인:")
df[['CO(GT)', 'CO_Double']].head()

<class 'pandas.core.series.Series'>
CO(GT) Series 첫 3개 값:
 0    2.6
1    2.0
2    2.2
Name: CO(GT), dtype: float64

새로운 열 추가 확인:

   CO(GT)  CO_Double
0     2.6        5.2
1     2.0        4.0
2     2.2        4.4
3     2.2        4.4
4     1.6        3.2

### **Indexers: 명시적 인덱스(loc)와 암묵적 인덱스(iloc)**
데이터를 추출하거나 슬라이싱할 때 활용되는 인덱서입니다.
* `iloc` (Integer-based Locating): 암묵적인 정수 인덱스(0, 1, 2...)를 참조하여 슬라이싱을 수행합니다.
* `loc` (Label-based Locating): 사용자가 명시적으로 정의한 인덱스 레이블을 참조하여 슬라이싱을 수행합니다.

In [17]:
# 암묵적 인덱싱: 처음 3개의 행과 처음 4개의 열을 정수로 슬라이싱
df.iloc[0:3, 0:4]

              Datetime  CO(GT)  PT08.S1(CO)  PT08.S2(NMHC)
0  2004-03-10 18:00:00     2.6       1360.0         1046.0
1  2004-03-10 19:00:00     2.0       1292.0          955.0
2  2004-03-10 20:00:00     2.2       1402.0          939.0

In [20]:
# 'Datetime'을 행의 명시적 인덱스로 설정
df_time_idx = df.set_index('Datetime')

# 레이블 기반 인덱싱 실습: 특정 시간(문자열 레이블)부터 시작하여 특정 열들만 슬라이싱
df_time_idx.loc['2004-03-10':'2004-03-15', ['CO(GT)', 'NOx(GT)', 'NO2(GT)']]

                     CO(GT)  NOx(GT)  NO2(GT)
Datetime
2004-03-10 18:00:00     2.6    166.0    113.0
2004-03-10 19:00:00     2.0    103.0     92.0
2004-03-10 20:00:00     2.2    131.0    114.0
2004-03-10 21:00:00     2.2    172.0    122.0
2004-03-10 22:00:00     1.6    131.0    116.0
...                     ...      ...      ...
2004-03-14 19:00:00     4.6    261.0    157.0
2004-03-14 20:00:00     5.9    325.0    173.0
2004-03-14 21:00:00     3.4    217.0    146.0
2004-03-14 22:00:00     2.1    146.0    121.0
2004-03-14 23:00:00     2.2    152.0    119.0

[102 rows x 3 columns]

### **마스킹 (Masking) 연산**
조건에 부합하는 특정 데이터만 걸러내기 위해 배열 스타일의 마스킹(Boolean Indexing) 연산을 사용할 수 있습니다.

In [5]:
# 조건: 이산화질소 센서 반응값 'PT08.S4(NO2)'가 1500을 초과하는 경우
mask_condition = df['PT08.S4(NO2)'] > 1500.0

# 마스크를 씌워 필터링된 새로운 DataFrame 생성
high_no2_df = df[mask_condition]

print(f"조건을 만족하는 관측치 개수: {len(high_no2_df)}개")
high_no2_df[['Datetime', 'PT08.S4(NO2)']].head()

조건을 만족하는 관측치 개수: 4062개

               Datetime  PT08.S4(NO2)
0   2004-03-10 18:00:00        1692.0
1   2004-03-10 19:00:00        1559.0
2   2004-03-10 20:00:00        1555.0
3   2004-03-10 21:00:00        1584.0
14  2004-03-11 08:00:00        1517.0

### **전치 행렬 (Transposed Matrix)**
필요에 따라 데이터셋을 재구조화할 때, 행과 열의 위치를 바꾸는 전치 행렬(`.T`)을 구할 수 있습니다.

In [7]:
# 데이터의 첫 3행을 추출한 후 행과 열을 전치(Transpose)
df_transposed = df.head(3).T
print("전치 행렬 결과:\n", df_transposed)

전치 행렬 결과:
                                  0                    1                    2
Datetime       2004-03-10 18:00:00  2004-03-10 19:00:00  2004-03-10 20:00:00
CO(GT)                         2.6                  2.0                  2.2
PT08.S1(CO)                 1360.0               1292.0               1402.0
PT08.S2(NMHC)               1046.0                955.0                939.0
NOx(GT)                      166.0                103.0                131.0
PT08.S3(NOx)                1056.0               1174.0               1140.0
NO2(GT)                      113.0                 92.0                114.0
PT08.S4(NO2)                1692.0               1559.0               1555.0
PT08.S5(O3)                 1268.0                972.0               1074.0
RH                            48.9                 47.7                 54.0
AH                          0.7578               0.7255               0.7502
C6H6(GT)                      11.9                  9.4                  9.0
CO_Double                      5.2                  4.0                  4.4

### **탐색적 데이터 분석 (Exploratory Data Analysis, EDA)**
데이터를 불러온 후에는 데이터의 형태, 속성, 통계량 등을 파악하여 데이터에 대한 이해도를 높여야 합니다.
* `.info()`: 데이터프레임의 행/열 개수, 각 열의 데이터 타입, 결측치가 아닌(Non-Null) 데이터의 개수 등 전반적인 정보를 출력합니다.
* `.describe()`: 수치형 데이터의 기술 통계량(개수, 평균, 표준편차, 최솟값, 4분위수, 최댓값)을 요약하여 보여줍니다.
* `.isnull().sum()`: 각 열마다 결측치(NaN)가 몇 개 존재하는지 확인합니다.

In [13]:
# 데이터 프레임의 기본 정보 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Datetime       9357 non-null   object
 1   CO(GT)         7765 non-null   float64
 2   PT08.S1(CO)    8991 non-null   float64
 3   PT08.S2(NMHC)  8991 non-null   float64
 4   NOx(GT)        7718 non-null   float64
 5   PT08.S3(NOx)   8991 non-null   float64
 6   NO2(GT)        7715 non-null   float64
 7   PT08.S4(NO2)   8991 non-null   float64
 8   PT08.S5(O3)    8991 non-null   float64
 9   RH             8991 non-null   float64
 10  AH             8991 non-null   float64
 11  C6H6(GT)       9357 non-null   float64
 12  CO_Double      7765 non-null   float64
dtypes: float64(12), object(1)
memory usage: 950.4+ KB

In [14]:
# 결측치(Missing Value) 개수 확인
print(df.isnull().sum())

Datetime            0
CO(GT)           1592
PT08.S1(CO)       366
PT08.S2(NMHC)     366
NOx(GT)          1639
PT08.S3(NOx)      366
NO2(GT)          1642
PT08.S4(NO2)      366
PT08.S5(O3)       366
RH                366
AH                366
C6H6(GT)            0
CO_Double        1592
dtype: int64

In [16]:
# 수치형 데이터의 기술 통계량 확인
df.describe()

,CO(GT),PT08.S1(CO),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),RH,AH,C6H6(GT),CO_Double
count,7765.000000,8991.000000,8991.000000,7718.000000,8991.000000,7715.000000,8991.000000,8991.000000,8991.000000,8991.000000,9357.000000,7765.000000
mean,2.127521,1099.833166,939.153376,246.896735,835.493605,113.091251,1456.264598,1022.906128,49.234201,1.025530,9.688704,4.255042
std,1.463171,217.080037,266.831429,212.979168,256.817320,48.370108,346.206794,398.484288,17.316892,0.403813,7.559785,2.926342
min,0.000000,647.000000,383.000000,2.000000,322.000000,2.000000,551.000000,221.000000,9.200000,0.184700,0.000000,0.000000
25%,1.000000,937.000000,734.500000,98.000000,658.000000,78.000000,1227.000000,731.500000,35.800000,0.736800,4.000000,2.000000
50%,1.800000,1063.000000,909.000000,180.000000,806.000000,109.000000,1463.000000,963.000000,49.600000,0.995400,7.900000,3.600000
75%,2.900000,1231.000000,1116.000000,326.000000,969.500000,142.000000,1674.000000,1273.500000,62.500000,1.313700,13.600000,5.800000
max,11.900000,2040.000000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000,88.700000,2.231000,63.700000,23.800000

### **EDA 심화: 변수 간의 상관관계 확인**
연속형 수치 데이터로 이루어진 경우, 변수들 간의 선형적 관계를 파악하기 위해 상관계수(Correlation Coefficient)를 확인할 수 있습니다.
* `.corr()`: 수치형 열 사이의 피어슨 상관계수(-1부터 1 사이의 값)를 계산합니다.

In [12]:
# 'Datetime'과 같은 문자열/시간 데이터는 상관계수 계산에서 제외하기 위해 수치형 데이터만 선택
numeric_df = df.select_dtypes(include=[np.number])

# 변수 간의 상관계수 행렬 출력 (예: CO(GT)와 PT08.S1(CO)의 상관관계 확인)
corr_matrix = numeric_df.corr()

corr_matrix

,CO(GT),PT08.S1(CO),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),RH,AH,C6H6(GT),CO_Double
CO(GT),1.000000,0.877203,0.914973,0.792557,-0.701703,0.679262,0.639470,0.851403,0.040218,0.065809,0.845144,1.000000
PT08.S1(CO),0.877203,1.000000,0.892964,0.713654,-0.771938,0.641529,0.682881,0.899324,0.114606,0.135324,0.883795,0.877203
PT08.S2(NMHC),0.914973,0.892964,1.000000,0.704435,-0.796703,0.646245,0.777254,0.880578,-0.090380,0.186933,0.981950,0.914973
NOx(GT),0.792557,0.713654,0.704435,1.000000,-0.655707,0.763111,0.233731,0.787046,0.221032,-0.149323,0.626638,0.792557
PT08.S3(NOx),-0.701703,-0.771938,-0.796703,-0.655707,1.000000,-0.652083,-0.538468,-0.796569,-0.056740,-0.232017,-0.735744,-0.701703
NO2(GT),0.679262,0.641529,0.646245,0.763111,-0.652083,1.000000,0.157360,0.708128,-0.091759,-0.335022,0.544039,0.679262
PT08.S4(NO2),0.639470,0.682881,0.777254,0.233731,-0.538468,0.157360,1.000000,0.591144,-0.032188,0.629641,0.765731,0.639470
PT08.S5(O3),0.851403,0.899324,0.880578,0.787046,-0.796569,0.708128,0.591144,1.000000,0.124956,0.070751,0.865689,0.851403
RH,0.040218,0.114606,-0.090380,0.221032,-0.056740,-0.091759,-0.032188,0.124956,1.000000,0.167971,-0.061681,0.040218
AH,0.065809,0.135324,0.186933,-0.149323,-0.232017,-0.335022,0.629641,0.070751,0.167971,1.000000,0.167972,0.065809
C6H6(GT),0.845144,0.883795,0.981950,0.626638,-0.735744,0.544039,0.765731,0.865689,-0.061681,0.167972,1.000000,0.845144
CO_Double,1.000000,0.877203,0.914973,0.792557,-0.701703,0.679262,0.639470,0.851403,0.040218,0.065809,0.845144,1.000000